### ISSUE TITLE
DeroHe Testnet issues. 

### ISSUE THREAD

**Issue by CaptainDero** [deroproject/derohe#1]
Please log all DeroHe Testnet issues/bugs here with screenshot and as much info as possible.

**Comment by CaptainDero** [comment]
> issue: while mining, miner sometimes reports "ERRO[44277] Blockwork could not decoded successfully () , err:%!s() n:0 {Blocktemplate_blob: Blockhashing_blob: Expected_reward:0 Difficulty:0 Height:0 Prev_Hash: Reserved_Offset:0 Epoch:0 Status:} "

Code added to throw more details on error. But at first glance it looks Disk error. 
Please keep monitoring for the error.

**Comment by CaptainDero** [comment]
> issue: explorer doesn't show size of coinbase transactions, and node status command doesn't give total supply (version 3.0.0-9.DEROHE.alpha+19122020)
Support of status command and total supply will be added.

**Comment by pojira** [comment]
i just saw something like the [Nelbert442 error](https://github.com/deroproject/derohe/issues/1#issuecomment-748540051):
```
WARN[6213] We must have queued 56e087c8181898a65950baa613e62503a79f93bd75885b8947c753c3ae3696e7, but we skipped it at height 638  com=P2P
WARN[6295] Rejecting Block, timestamp is too much into future, make sure that system clock is correct  blid=0ef66b4b6c1bbdcc15f7217e5b869b4db08c2cf744191c3589b14724f0f0256b com=CORE
WARN[6296] We must have queued c18632a50730101f7427f2feb755c3c5189c521f7c50c6ce1fb847c7c20b39bc, but we skipped it at height 640  com=P2P
INFO[6306] Block 766f9c60c68e2ab5160720074b047c71b30bc039a875f9831144ed328ee9f460 successfully accepted at height 644, Notifying Network  com=CORE
INFO[6306] Submitted block 766f9c60c68e2ab5160720074b047c71b30bc039a875f9831144ed328ee9f460 accepted  com=RPC
INFO[6369] Block 2e3c74c9399cf09b4d0cf53e03294405069a09dac3b5128bb142b0c2efb573a8 successfully accepted at height 646, Notifying Network  com=CORE
INFO[6369] Submitted block 2e3c74c9399cf09b4d0cf53e03294405069a09dac3b5128bb142b0c2efb573a8 accepted  com=RPC
INFO[6523] Block 746168d402af7fc9587f47d4d3e78c7f60621f15d924eb72f4c760d491ef2a1a successfully accepted at height 649, Notifying Network  com=CORE
INFO[6523] Submitted block 746168d402af7fc9587f47d4d3e78c7f60621f15d924eb72f4c760d491ef2a1a accepted  com=RPC
WARN[7028] Rejecting Block, timestamp is too much into future, make sure that system clock is correct  blid=6cfb39a12703fe0d49d09f9c1d304f2897165de3ed5faf6ca97d1c5686e17902 com=CORE
WARN[7029] We must have queued 9a980535d6f476058b9d6810bf7021ce9ac3561aada8f85ed72d5d26c6e02937, but we skipped it at height 661  com=P2P
INFO[7372] Block fcfa3c70468000cd561f9d3c31ffff7a2f48f49f2d6457912eb400a6a07a1c86 successfully accepted at height 673, Notifying Network  com=CORE
INFO[7372] Submitted block fcfa3c70468000cd561f9d3c31ffff7a2f48f49f2d6457912eb400a6a07a1c86 accepted  com=RPC
WARN[7484] fError deserialiing block, block id 6900b6760c10738aafd83f99a0d3dbf1ef4360a5f70d6eb7e9db9321bce0512c len(data) 0 data  err Block Header could not be parsed Invalid Major Version in Block

  com=CORE
WARN[7485] fError deserialiing block, block id 6900b6760c10738aafd83f99a0d3dbf1ef4360a5f70d6eb7e9db9321bce0512c len(data) 0 data  err Block Header could not be parsed Invalid Major Version in Block

  com=CORE
WARN[7485] fError deserialiing block, block id 6900b6760c10738aafd83f99a0d3dbf1ef4360a5f70d6eb7e9db9321bce0512c len(data) 0 data  err Block Header could not be parsed Invalid Major Version in Block

  com=CORE
WARN[7486] fError deserialiing block, block id 6900b6760c10738aafd83f99a0d3dbf1ef4360a5f70d6eb7e9db9321bce0512c len(data) 0 data  err Block Header could not be parsed Invalid Major Version in Block

  com=CORE
WARN[7487] fError deserialiing block, block id 6900b6760c10738aafd83f99a0d3dbf1ef4360a5f70d6eb7e9db9321bce0512c len(data) 0 data  err Block Header could not be parsed Invalid Major Version in Block

  com=CORE
WARN[7490] fError deserialiing block, block id 6900b6760c10738aafd83f99a0d3dbf1ef4360a5f70d6eb7e9db9321bce0512c len(data) 0 data  err Block Header could not be parsed Invalid Major Version in Block

  com=CORE
WARN[7490] fError deserialiing block, block id 6900b6760c10738aafd83f99a0d3dbf1ef4360a5f70d6eb7e9db9321bce0512c len(data) 0 data  err Block Header could not be parsed Invalid Major Version in Block

  com=CORE
WARN[7490] fError deserialiing block, block id 6900b6760c10738aafd83f99a0d3dbf1ef4360a5f70d6eb7e9db9321bce0512c len(data) 0 data  err Block Header could not be parsed Invalid Major Version in Block

  com=CORE
WARN[7490] fError deserialiing block, block id 6900b6760c10738aafd83f99a0d3dbf1ef4360a5f70d6eb7e9db9321bce0512c len(data) 0 data  err Block Header could not be parsed Invalid Major Version in Block

  com=CORE
DERO HE: 674/690 [674/690] P 13 TXp 0:0 NW 2.8 KH/s > TESTNET>> panic: Block Header could not be parsed Invalid Major Version in Block



goroutine 43 [running]:
github.com/deroproject/derohe/blockchain.(*Blockchain).Calculate_Height_At_Tips(0xc0001025a0, 0xc001487840, 0x2, 0x2, 0xc0003e9750)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/store.go:188 +0xff
github.com/deroproject/derohe/blockchain.(*Blockchain).Get_Difficulty_At_Tips(0xc0001025a0, 0xc001487840, 0x2, 0x2, 0x0)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/difficulty.go:175 +0x1a3
github.com/deroproject/derohe/blockchain.(*Blockchain).Get_Difficulty(0xc0001025a0, 0x0)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/blockchain.go:1039 +0x39
github.com/deroproject/derohe/blockchain.(*Blockchain).Get_Network_HashRate(...)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/blockchain.go:1053
main.main.func4(0xc0001025a0, 0xc0000a3400)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/derod/main.go:313 +0x317
created by main.main
        /usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/derod/main.go:254 +0x9b7
```

the clock is sync'd on that machine.

**Comment by CaptainDero** [comment]
P2P layer is being worked upon along with above error.

**Comment by netwarp** [comment]
suggestion: an option to create an offline transaction (like in the previous version)

**Comment by fm407** [comment]
`WARN[13785] Recovered while Verifying transaction, failed verification, Stack trace below  com=CORE txid=0000000000000000000000000000000000000000000000000000000000000000
WARN[13785] Stack trace
goroutine 84141 [running]:
runtime/debug.Stack(0xc0000667d0, 0xa68489, 0x4d)
        /home/github/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/deroproject/derohe/blockchain.(*Blockchain).Verify_Transaction_NonCoinbase.func1(0x0, 0x0, 0x0, 0x0, 0xc0000936b0)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/transaction_verify.go:131 +0x19b
panic(0x9803a0, 0xb15a90)
        /home/github/local/go/src/runtime/panic.go:967 +0x15d
github.com/deroproject/derohe/blockchain.(*Blockchain).Verify_Transaction_NonCoinbase(0xc0004d60f0, 0x1, 0xc0010d49a0, 0xb00)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/transaction_verify.go:197 +0xe22
github.com/deroproject/derohe/blockchain.(*Blockchain).Add_TX_To_Pool(0xc0004d60f0, 0xc0010d49a0, 0x76186df00)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/blockchain.go:1189 +0x6ab
github.com/deroproject/derohe/p2p.(*Connection).Handle_Notification_Transaction(0xc001722900, 0xc00043bb00, 0x83a, 0x83a)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/p2p/notification.go:65 +0x406
github.com/deroproject/derohe/p2p.Handle_Connection(0xb32dc0, 0xc0000f4380, 0xc0011e0030, 0xc000160001)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/p2p/connection_handler.go:423 +0xa4c
created by github.com/deroproject/derohe/p2p.P2P_Server_v2
        /usr/home/github/gowork/src/github.com/deroproject/derohe/p2p/controller.go:382 +0x521
  com=CORE
INFO[13881] Chain Height 1400                             blid=36b32628c9cbe956bc16066387844b03c8f6ea19a798edf0f16765b4f97d3ede com=CORE
INFO[20719] Chain Height 1600                             blid=dbf576cd40993e20b0c676d9e755e82d7ff6021ef72a0026fc0fca16e39a2d65 com=CORE
`
`deto1qxs 1775/1775 7.49995 | 0.00000  TESTNET>>> exit
panic: close of nil channel

goroutine 1 [running]:
github.com/deroproject/derohe/walletapi.(*Wallet).Close_Encrypted_Wallet(0xc000104a80)
        /home/derohe/go/src/github.com/deroproject/derohe/walletapi/db.go:368 +0x36
main.handle_easymenu_post_open_command(0xc00000f580, 0xc0004728d0, 0x4, 0x0)
        /home/derohe/go/src/github.com/deroproject/derohe/cmd/dero-wallet-cli/easymenu_post_open.go:257 +0x698
main.main()
        /home/derohe/go/src/github.com/deroproject/derohe/cmd/dero-wallet-cli/main.go:329 +0x9df
`

`deto1qxs 1014/1014 8.00000 | 0.00000  TESTNET>>> 8
panic: close of nil channel

goroutine 1 [running]:
github.com/deroproject/derohe/walletapi.(*Wallet).Close_Encrypted_Wallet(0xc000083200)
        /home/derohe/go/src/github.com/deroproject/derohe/walletapi/db.go:368 +0x36
main.handle_easymenu_post_open_command(0xc00000e4a0, 0xc000b36938, 0x1, 0x0)
        /home/derohe/go/src/github.com/deroproject/derohe/cmd/dero-wallet-cli/easymenu_post_open.go:245 +0x1ccb
main.main()
        /home/derohe/go/src/github.com/deroproject/derohe/cmd/dero-wallet-cli/main.go:329 +0x9df
`

**Comment by CaptainDero** [comment]
Delete old testnet folder and update binaries to latest release 3.

**Comment by Ez3kiel-2020** [comment]
Same here (menu 0 and 8) with release 3.

![Capture d’écran du 2020-12-22 12-09-10](https://user-images.githubusercontent.com/76476566/102882356-8be34f80-444e-11eb-9270-eaa967eda10a.png)

**Comment by darkrevol** [comment]
Error when try to transfer  all dero on wallet but wallet is empty (zero balance), wallet is crashing

panic: TX verification failed !!!!!!!!!!

goroutine 1 [running]:
github.com/deroproject/derohe/walletapi.BuildTransaction(0xc000414300, 0xc000629768, 0xc0000065f0, 0xc0006082e0, 0xc000004f80, 0x0, 0xfffffffffffffffb, 0xc000622ad0, 0x1, 0x0, ...)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/walletapi/transaction_build.go:153 +0x1e2f
github.com/deroproject/derohe/walletapi.(*Wallet).Transfer(0xc000604c00, 0xc000629d38, 0x1, 0x1, 0xc000629ae8, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/walletapi/wallet_transfer.go:214 +0xe26
main.handle_easymenu_post_open_command(0xc000356080, 0xc000456340, 0x2, 0x0)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/dero-wallet-cli/easymenu_post_open.go:219 +0x459
main.main()
        /usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/dero-wallet-cli/main.go:329 +0x9de

**Comment by Ez3kiel-2020** [comment]
Just after deleting the testnet folder, during derod sync : 
![Capture d’écran du 2020-12-22 17-41-57](https://user-images.githubusercontent.com/76476566/102912379-99fc9480-447d-11eb-9f3d-7c1e42b512f8.png)

**Comment by fm407** [comment]
deleted folder and updated binaries, still crashing:

```
WARN[30978] Stack trace
goroutine 140843 [running]:
runtime/debug.Stack(0xc000162140, 0xa68489, 0x4d)
        /home/github/local/go/src/runtime/debug/stack.go:24 +0x9d
github.com/deroproject/derohe/blockchain.(*Blockchain).Verify_Transaction_NonCoinbase.func1(0x0, 0x0, 0x0, 0x0, 0xc0002b96b0)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/transaction_verify.go:131 +0x19b
panic(0x9803a0, 0xb15a90)
        /home/github/local/go/src/runtime/panic.go:967 +0x15d
github.com/deroproject/derohe/blockchain.(*Blockchain).Verify_Transaction_NonCoinbase(0xc0000d45a0, 0x1, 0xc001b9fb80, 0x1800)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/transaction_verify.go:197 +0xe22
github.com/deroproject/derohe/blockchain.(*Blockchain).Add_TX_To_Pool(0xc0000d45a0, 0xc001b9fb80, 0xdecb72300)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/blockchain/blockchain.go:1189 +0x6ab
github.com/deroproject/derohe/p2p.(*Connection).Handle_Notification_Transaction(0xc001cc6180, 0xc002206000, 0x134b, 0x134b)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/p2p/notification.go:65 +0x406
github.com/deroproject/derohe/p2p.Handle_Connection(0xb32dc0, 0xc00083e000, 0xc001b08570, 0xc000470001)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/p2p/connection_handler.go:423 +0xa4c
created by github.com/deroproject/derohe/p2p.P2P_Server_v2
        /usr/home/github/gowork/src/github.com/deroproject/derohe/p2p/controller.go:382 +0x521
  com=CORE
INFO[35035] Chain Height 6200                             blid=c56b0b818a4bde1a30721d4dc6e8dda6dd6d77ae5781c61b6d235374c7301b50 com=CORE
DERO HE: 6285/6386 [6284/6385] P 12 TXp 2:0 NW 800 H/s > TESTNET>>
```

**Comment by JaernStaang** [comment]
Got the following crash after transferring all balance to another wallet, waited a couple of blocks until balance was one again and tried to transfer 1 dero to the same wallet I previously transferred all dero to. 

-------------------------------

panic: TX verification failed !!!!!!!!!!

goroutine 1 [running]:
github.com/deroproject/derohe/walletapi.BuildTransaction(0xc000518278, 0xc0004435d8, 0xc0011dc2a8, 0xc000fe8840, 0xc00034b660, 0x186a0, 0x186a0, 0xc001682680, 0x0, 0x2, ...)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/walletapi/transaction_build.go:153 +0x1e2f
github.com/deroproject/derohe/walletapi.(*Wallet_Memory).Transfer(0xc000108680, 0xc000443c90, 0x1, 0x1, 0xc0004439c0, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/walletapi/wallet_transfer.go:222 +0xf13
main.handle_easymenu_post_open_command(0xc00069a0a0, 0xc0004a4f40, 0x1, 0x0)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/dero-wallet-cli/easymenu_post_open.go:185 +0x1ad6
main.main()
        /usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/dero-wallet-cli/main.go:329 +0xa35

**Comment by JaernStaang** [comment]
Tried to replicate above crash, and this time it crashed when I tried to transfer all balance (12) to another wallet. 

----------------------------------------------------------
panic: TX verification failed !!!!!!!!!!

goroutine 1 [running]:
github.com/deroproject/derohe/walletapi.BuildTransaction(0xc0013e0198, 0xc0010e75d8, 0xc0013e0260, 0xc000404e20, 0xc0004051c0, 0x55730, 0x61a7b, 0xc0015ce640, 0x0, 0x0, ...)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/walletapi/transaction_build.go:153 +0x1e2f
github.com/deroproject/derohe/walletapi.(*Wallet_Memory).Transfer(0xc001100000, 0xc0010e7c58, 0x1, 0x1, 0xc0010e79b8, 0x1, 0x1, 0x0, 0x0, 0x0, ...)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/walletapi/wallet_transfer.go:222 +0xf13
main.handle_easymenu_post_open_command(0xc00051e180, 0xc00067f3e8, 0x2, 0x0)
        /usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/dero-wallet-cli/easymenu_post_open.go:219 +0x458
main.main()
        /usr/home/github/gowork/src/github.com/deroproject/derohe/cmd/dero-wallet-cli/main.go:329 +0xa35

**Comment by Ez3kiel-2020** [comment]
Crash when trying to send full balance with an empty wallet :
![Capture d’écran du 2020-12-27 19-05-27](https://user-images.githubusercontent.com/76476566/103177004-8a62be80-4876-11eb-9ddf-a00ecf9c107c.png)

**Comment by CaptainDero** [comment]
Some  nodes on current testnet(**Version 3.0.0-23.DEROHE.alpha+27122020**) got stucked on 4019/4193 . 
Request to share your testnet folder.

**Comment by CaptainDero** [comment]
Release7 updated with P2P fixes. https://github.com/deroproject/derohe/releases/tag/Release7

**Comment by CaptainDero** [comment]
Release8 Updated with- **Transaction verification cache enabled**.  It will reduce load on nodes.
 https://github.com/deroproject/derohe/releases/tag/Release8

**Comment by Ez3kiel-2020** [comment]
just for information: crash encountered when restarting the daemon. the next reboot was OK. (release 8)
![Capture d’écran du 2020-12-30 22-36-26](https://user-images.githubusercontent.com/76476566/103382693-3236f100-4af0-11eb-8438-01e99a87622c.png)

**Comment by Bugboom** [comment]
Question 1: I am Check the transaction on the DERO testnet Explorer, the transaction data in the block is displayed as 0. How do I know that my account transaction is protected by the homomorphic encryption?
Question 2: Can I perform on the test network, for example, as you said, whether the disk storage occupied by larger exchanges is the same as you said?(Note that, Even after 1 trillion transactions, 1 billion accounts will consume 800GB only, If history is not maintained, and everything still will be in proved state using merkle roots. And so, Even Raspberry Pi can host the entire chain.)

**Comment by Bugboom** [comment]
Can I learn more about how you achieved Homomorphic Ring Confidential Transactions？

I am doing academic research related to blockchain on the HE blockchain. You are doing a very cool thing and leading the world.

**Comment by CaptainDero** [comment]
> Question 1: I am Check the transaction on the DERO testnet Explorer, the transaction data in the block is displayed as 0. How do I know that my account transaction is protected by the homomorphic encryption?
> Question 2: Can I perform on the test network, for example, as you said, whether the disk storage occupied by larger exchanges is the same as you said?(Note that, Even after 1 trillion transactions, 1 billion accounts will consume 800GB only, If history is not maintained, and everything still will be in proved state using merkle roots. And so, Even Raspberry Pi can host the entire chain.)

**Ans 1]**
 Check following code for [Homomorphic Encryption](https://github.com/deroproject/derohe/blob/main/blockchain/transaction_execute.go#L83)  

```
for i := range tx.Statement.Publickeylist_compressed {
            if balance_serialized, err := balance_tree.Get(tx.Statement.Publickeylist_compressed[i][:]); err == nil {

                balance := new(crypto.ElGamal).Deserialize(balance_serialized)
                echanges := crypto.ConstructElGamal(tx.Statement.C[i], tx.Statement.D)

                balance = balance.Add(echanges)                         // homomorphic addition of changes
                balance_tree.Put(tx.Statement.Publickeylist_compressed[i][:], balance.Serialize()) // reserialize and store
            } else {
                panic(err) // if balance could not be obtained panic ( we can never reach here, otherwise how tx got verified)
            }
```

**Ans 2]**
Yeah please go ahead and report your findings. 
Let us know if you require any help in setting up the testnet. 
Better to use at-least 1/10G network and SSD/NVME latest disks for faster results.

**Comment by CaptainDero** [comment]
As new testnet released, Please continue discussion [here](https://github.com/deroproject/derohe/issues/3).
