### ISSUE TITLE
SC not found and literal not terminated

### ISSUE THREAD

**Issue by k7n2g** [deroproject/derohe#109]
ubuntu 18.04
16GB mem
ssd 1.2tb

Daemon shows errors while syncing this is binary install latest guys 114

DERO HE: 521162/521162 [1580986/1580986] P 34 TXp 0:0 NW 19.980 MH/s >MN 0  MAINNET 0 0s|0s|-12ms>> code:1:1: literal not terminated
code:1:1: invalid char literal
02/02 12:39:48  ERROR   CORE    SC not found    {"scid": "eb0bfd7205a8753282ebf62a103451cdb30f161db301db742b50dc1b9f2a5c88"}
DERO HE: 1230955/1230955 [1585938/1585938] P 34 TXp 0:0 NW 145.006 MH/s >MN 0  MAINNET 0 0s|0s|5ms>> code:1:919: invalid char literal
code:1:988: invalid char literal
code:1:1480: invalid char literal
DERO HE: 1399642/1399642 [1587619/1587619] P 31 TXp 0:0 NW 359.252 MH/s >MN 0  MAINNET 0 0s|0s|-15ms>> code:2:1: literal not terminated
code:2:1: invalid char literal
DERO HE: 1399739/1399739 [1587622/1587622] P 31 TXp 0:0 NW 290.734 MH/s >MN 0  MAINNET 0 0s|0s|-10ms>> code:2:3: literal not terminated
code:2:3: invalid char literal
DERO HE: 1400553/1400553 [1587640/1587640] P 31 TXp 0:0 NW 257.687 MH/s >MN 0  MAINNET 0 0s|0s|-18ms>> code:2:3: literal not terminated
code:2:3: invalid char literal
DERO HE: 1402323/1402323 [1587659/1587659] P 31 TXp 0:0 NW 287.147 MH/s >MN 0  MAINNET 0 0s|0s|-7ms>> code:2:3: literal not terminated
code:2:3: invalid char literal
DERO HE: 1413052/1413052 [1587779/1587779] P 32 TXp 0:0 NW 336.409 MH/s >MN 0  MAINNET 0 0s|0s|-4ms>>

**Comment by Slixe** [comment]
Ignore it, all good

**Comment by k7n2g** [comment]
Thanks for reply Slixe   Just giving you feedback  as supporting this initiative
