### ISSUE TITLE
RPC GetSC bug - Fetching keys with uint64 value overwrites the array

### ISSUE THREAD

**Issue by g45t345rt** [deroproject/derohe#112]
Should be `result.ValuesString` instead of `result.ValuesUint64`

https://github.com/deroproject/derohe/blob/358fab62bdf443a02358c67b322f0685ec072303/cmd/derod/rpc/rpc_dero_getsc.go#L174

**Comment by CaptainDero** [comment]
Thank you @g45t345rt.
Fixed in latest release 116.
