### ISSUE TITLE
Feature Request: DVM Helper Functions (namehash, string length)

### ISSUE THREAD

**Issue by sausman** [deroproject/derohe#14]
I am thinking through a smart contract where names can be registered (similar to ENS). A couple helper functions I think would be nice:

- `NAMEHASH(string)` or similar hashing function (https://docs.ens.domains/contract-api-reference/name-processing)
- `LENGTH(string)` or similar function (for tiered pricing based on length)

**Comment by CaptainDero** [comment]
Added. Please check https://github.com/deroproject/documentation/tree/master/DVMDOCS/examples/nameservice
