### ISSUE TITLE
Wallet RPC/WebSocket doesn't care about --rpc-login parameter

### ISSUE THREAD

**Issue by Peppinux** [deroproject/derohe#17]
Version: **DERO-HE STARGATE Testnet Release35**

Title pretty much sums it up.

When --rpc-login=<username:password> is set as a wallet parameter, RPC/WebSocket requests receive successful responses even if no (or wrong) Basic Auth params are provided in the request.

This poses a - minor, no need to panic for anyone reading here, but developers should solve this - security risk, since any wallet with an --rpc-server online could receive unwanted calls from malicious locally running software without being able to protect itself with working password authentication.

As a bonus, I would add a feature where critical RPC methods like "transfer" should require manual confirmation from the user from within the wallet.

**Comment by CaptainDero** [comment]
Noted.

**Comment by CaptainDero** [comment]
Added, will be there in next release.

**Comment by Peppinux** [comment]
This issue has to be reopened/partially fixed.

The current **(STARGATE Release42**) implementation of Basic Auth works great for simple RPC, as it now requires username and password for calls, **but is far from ideal for WebSockets**.

Why? In a nutshell, it technically works, and that can be tested with software like Postman: you add your custom `Authorization` header, your connection to the WS is good.

**However**, a real life scenario where you use the browser [WebSocket API](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) will always reject your connection because there's no way to include extra headers (like `Authorization`) to a [WebSocket ](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket) connection. The only header that can be set is `Sec-WebSocket-Protocol`, as you can read here https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api/4361358#4361358
You used to be able to use something like `new WebSocket("ws://username:password@example.com")` but this is now deprecated, unfortunately.

Therefore, we need to change the way authorization is handled in WS server, otherwise it will be impossible to connect to a wallet from the browser when --rpc-login is set. This will force users to not use the --rpc-login param and become vulnerable to threats from any software running on their machine.

Also, regarding vulnerability, I repeat that, whether --rpc-login is set or not, methods that can spend wallets' funds like `transfer` and `scinvoke` should require manual confirmation from the user from within the wallet, unless otherwise specified by the user by setting some additional param. This way, even "trusted" software won't be able to spend coins maliciously.

**Comment by CaptainDero** [comment]
Fixed. Please check and report in latest release 43.

**Comment by Peppinux** [comment]
**Yes Capt, the error with WS I reported on Discord is now fixed. Daemon doesn't crash anymore. Great!**

But the other issues in my [comment](https://github.com/deroproject/derohe/issues/17#issuecomment-1035709080) haven't been addressed yet:
> However, a real life scenario where you use the browser [WebSocket API](https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API) will always reject your connection because there's no way to include extra headers (like `Authorization`) to a [WebSocket ](https://developer.mozilla.org/en-US/docs/Web/API/WebSocket/WebSocket) connection. The only header that can be set is `Sec-WebSocket-Protocol`, as you can read here https://stackoverflow.com/questions/4361173/http-headers-in-websockets-client-api/4361358#4361358 
You used to be able to use something like `new WebSocket("ws://username:password@example.com")` but this is now deprecated, unfortunately.
Therefore, we need to change the way authorization is handled in WS server, otherwise it will be impossible to connect to a wallet from the browser when --rpc-login is set. This will force users to not use the --rpc-login param and become vulnerable to threats from any software running on their machine.

**Possible fixes:**
- Using the `Sec-WebSocket-Protocol` to authorize (although out of specification).
- Using URL query params to pass `--rpc-login`'s username and password. 

> Also, regarding vulnerability, I repeat that, whether --rpc-login is set or not, methods that can spend wallets' funds like `transfer` and `scinvoke` should require manual confirmation from the user from within the wallet, unless otherwise specified by the user by setting some additional param. This way, even "trusted" software won't be able to spend coins maliciously.

**As I already said in Discord, possible solutions:**
- Just like the already existing `--unlocked` param, you could add `--rpc-unlocked` for the users that don't want to manually confirm.
- Or `--rpc-locked`, if you want to go the other way around.

**Comment by g45t345rt** [comment]
+1 This should be reopened.

`rpc-unlocked` should be implemented and false by default. Right now, I can easily create a website that connects to the user cli wallet and transfer all the coins instantly. Asuming the `--rpc-server` is enabled, `--rpc-login` is not set and default rpc port is used.
