### ISSUE TITLE
Cannot import packages from derohe into an external project because of Graviton module error

### ISSUE THREAD

**Issue by Peppinux** [deroproject/derohe#18]
Version: **DERO-HE STARGATE Testnet Release36**

I'll try and make this issue as reproducible as I can using a practical example.

Let's say I want to build a little test service for Dero using Golang. As shown in the [pong_server example](https://github.com/deroproject/derohe/blob/main/cmd/rpc_examples/pong_server/pong_server.go), I may need to import some packages like `github.com/deroproject/derohe/rpc`, `github.com/deroproject/derohe/walletapi`, `github.com/deroproject/derohe/transaction`, etc.

So I go ahead, create my `test_service` dir inside my `~/Projects` dir, cd into it and create a dummy file `main.go`:
```
package main

import (
	"fmt"

	"github.com/deroproject/derohe/rpc"
)

func main() {
	fmt.Println(rpc.RPC_COMMENT)
}
```

I now initialize my module:
`go mod init test_service`
`go mod tidy`
And try to build it
`go build`
but **here's where I get the error**:
```
# github.com/deroproject/derohe/cryptography/crypto
../../go/pkg/mod/github.com/deroproject/derohe@v0.0.0-20211209155901-d2e9638394cd/cryptography/crypto/protocol_structures.go:65:18: undefined: graviton.Sum
```

I understand this is caused by the fact that graviton.Sum is, indeed, undefined in the official [Graviton library](https://github.com/deroproject/graviton), whereas it is defined in the [special.go](https://github.com/deroproject/derohe/blob/main/vendor/github.com/deroproject/graviton/special.go) file of the vendorized Graviton library that derohe uses internally. Therefore, there is a mismatch between the library that `go mod tidy` fetches from GitHub, and the internal library that derohe uses.

So I try and run `go mod vendor` and then `go build` again, but this only causes a difference in the path where the error occurs:
```
# github.com/deroproject/derohe/cryptography/crypto
vendor/github.com/deroproject/derohe/cryptography/crypto/protocol_structures.go:65:18: undefined: graviton.Sum
```

Now, **this issue is bypassable** by replacing the contents of `~/Projects/test_service/vendor/github.com/deroproject/graviton` with the manually downloaded ones from `https://github.com/deroproject/derohe/blob/main/vendor/github.com/deroproject/graviton`, which include the `special.go` file and, therefore, the wanted `graviton.Sum` function. Now my build doesn't fail and I get my working test_service binary.

But this is just a hack, useful to keep my work going, but still an inelegant hack.
That's why I think it needs a real solution, that will also help other developers not get stuck with the same problem without knowing what to do.
I don't know what the best fix is, maybe updating the official Graviton repo, maybe something else, but, as minor as the issue is, the devs should look into it.

Note: this issue doesn't present itself with the [pong_server example](https://github.com/deroproject/derohe/blob/main/cmd/rpc_examples/pong_server/pong_server.go) only because that's built from within the derohe project, so it knows what's the right graviton library to use.

**Comment by CaptainDero** [comment]
Fixed. Updated Graviton repo.
