### ISSUE TITLE
disable integrator_address

### ISSUE THREAD

**Issue by DarkRiDDeR** [deroproject/derohe#182]
is it possible to disable integrator_address to mine without commission on the node?

**Comment by itsMarcoSolis** [comment]
Integrator node gets integrator rewards, so you can use your own address/node to collect all rewards while mining.

**Comment by DarkRiDDeR** [comment]
I'm too kind and want to turn off the reward

**Comment by itsMarcoSolis** [comment]
Reward is part of the protocol, there is no way to turn it off. What you can do is reward yourself by running your own node and setting the integrator address to your node address.
