### ISSUE TITLE
A couple of little issues with rpc.RPC_COMMENT

### ISSUE THREAD

**Issue by Peppinux** [deroproject/derohe#19]
Version: **DERO-HE STARGATE Testnet Release36**

1. The most important of them: this one still hasn't been fixed https://github.com/deroproject/derohe/issues/3#issuecomment-819955750
It means the Integrated Message (Comment) of an Integrated Address generated by a service will be ignored when the TX is sent.
Proof with screenshots:
https://media.discordapp.net/attachments/726125778533875742/832030175918030908/Transfer.png
https://media.discordapp.net/attachments/726125778533875742/832030238715936788/NoMessageInTX.png
IMO, still easily fixable by adding `arguments = append(arguments, rpc.Argument{rpc.RPC_COMMENT, rpc.DataString, a.Arguments.Value(rpc.RPC_COMMENT, rpc.DataString)})` to https://github.com/deroproject/derohe/blob/main/cmd/dero-wallet-cli/easymenu_post_open.go#L245

2. I think "arguments = append(arguments, rpc.Argument{**"Comment"**, rpc.DataString, a.Arguments.Value(rpc.RPC_COMMENT, rpc.DataString)})" should be replaced with "arguments = append(arguments, rpc.Argument{**rpc.RPC_COMMENT**, rpc.DataString, a.Arguments.Value(rpc.RPC_COMMENT, rpc.DataString)})" on line https://github.com/deroproject/derohe/blob/main/cmd/dero-wallet-cli/easymenu_post_open.go#L319 in order to save bytes and allow for longer messages (since len("C") < len("Comment").

**Comment by CaptainDero** [comment]
Fixed.
