### ISSUE TITLE
Simulator and Smart Contracts: error interpreting line

### ISSUE THREAD

**Issue by Peppinux** [deroproject/derohe#20]
Version: **DERO-HE STARGATE Testnet Release36**

Trying to install the [token example SC](https://github.com/deroproject/documentation/blob/master/DVMDOCS/examples/token/token.bas) using the [simulator](https://github.com/deroproject/derohe/tree/main/cmd/simulator) returns the following error:
```
interpreting line [STORE ( "owner" , SIGNER ( ) )]   err:'%!s(<nil>)'
interpreting line [SEND_ASSET_TO_ADDRESS ( SIGNER ( ) , 1600000 , SCID ( ) )]   err:'%!s(<nil>)'
interpreting line [RETURN 0]   err:'%!s(<nil>)'
```
Then the contract actually gets deployed to the chain, but calling any function produces the same behavior.
Example calling _IssueTOKENX_:
```
interpreting line [SEND_ASSET_TO_ADDRESS ( SIGNER ( ) , DEROVALUE ( ) , SCID ( ) )]   err:'%!s(<nil>)'
interpreting line [RETURN 0]   err:'%!s(<nil>)'
```

Fortunately, this behavior **DOES NOT** happen when installing/using smart contracts with the actual testnet daemon. The fact that that works correctly is more important.
Still, a 100% working simulator would be ideal for developers.

**Comment by CaptainDero** [comment]
Actually not a bug and added proper formatting.
