### ISSUE TITLE
Issues with retrieving token's balance and transfers from wallet and RPC

### ISSUE THREAD

**Issue by Peppinux** [deroproject/derohe#21]
Version: **DERO-HE STARGATE Testnet Release36**

What I did: installed a token SC (SCID: b2e6122e52850a79fa997023ee713d47882002b94b99c4da4a385ec374ec27ba) and played around sending tokens between wallets.

My issues:

#### Trying getting my token balance
:heavy_check_mark: Typing `balance b2e6122e52850a79fa997023ee713d47882002b94b99c4da4a385ec374ec27ba` inside the CLI wallet prompt returns the correct amount:
`SCID b2e6122e52850a79fa997023ee713d47882002b94b99c4da4a385ec374ec27ba Balance    : 1.60000`

:x: Calling the wallet RPC `curl http://127.0.0.1:40403/json_rpc -d '{"jsonrpc": "2.0","id": "0","method": "GetBalance","params": {"scid": "b2e6122e52850a79fa997023ee713d47882002b94b99c4da4a385ec374ec27ba"}}' -H 'Content-Type:application/json'` returns the wrong amount:
`{"jsonrpc":"2.0","id":"0","result":{"balance":0,"unlocked_balance":0}}`

#### Trying getting my **token transfers**
:x: Typing `show_transfers b2e6122e52850a79fa997023ee713d47882002b94b99c4da4a385ec374ec27ba` insde the CLI wallet returns NO transfers (there should be plenty):
`ERROR	wallet	No transfers available`

:x: Calling the wallet RPC `curl http://127.0.0.1:40403/json_rpc -d '{"jsonrpc": "2.0","id": "0","method": "GetTransfers","params": {"scid": "b2e6122e52850a79fa997023ee713d47882002b94b99c4da4a385ec374ec27ba","in": true,"out": true}}' -H 'Content-Type:application/json'` returns no transfers as well:
`{"jsonrpc":"2.0","id":"0","result":{}}`

:heavy_plus_sign: Nice to have additional features:
- Wallet CLI:
  - New option, like number "13", but for tokens: "Show **tokens** transaction history".
  - New option that shows both DERO and tokens transaction history. A mix between "13" and the new proposed one.
  - New prompt command `show_all_transfers` that shows both DERO and tokens transaction history.
- RPC
  - New method, `GetAllTransfers`, that fetches ALL of the DERO and tokens transactions, without the need to specify any token SCID. Like `show_all_transfers` but for RPC.

**Comment by CaptainDero** [comment]
First case, Issue wallet rescan.

Additional features mentioned above are not possible.
