### ISSUE TITLE
changelog

### ISSUE THREAD

**Issue by snipeTR** [deroproject/derohe#33]
Why isn't there any change log? It is difficult to understand what changes have been made.

**Comment by DankFC** [comment]
https://github.com/deroproject/derohe/commit/3acbbee23416e24cc07b33de91a46c2ecc1a8ade

**Comment by DankFC** [comment]
https://github.com/deroproject/derohe/commit/3acbbee23416e24cc07b33de91a46c2ecc1a8ade

**Comment by CaptainDero** [comment]
Till recently lots of changes on very short notices. 
Also most of the testers/DEVS were happy with commit diffs.
In future there will change logs.
