### ISSUE TITLE
feature request: external IP change causes delay in re-building peer node list

### ISSUE THREAD

**Issue by davidj-android** [deroproject/derohe#38]
I lost power to my modem which caused an IP change. I noticed that the peer list in my node dropped way down.

Is it possible to adda domain-name param to the node start up, e.g.

--p2p-domain=my.domain.name

So that if there's an IP change to a node, the peer list can be quickly loaded back up?

**Comment by davidj-android** [comment]
In thinking more about this and the notion that you can run your own node - many of us will be on casual devices on networks where our IPs could change frequently. I can use a dynamic dns updater to keep my IP associated with a domain, but not everyone will want or have the understanding of how to do this...

**Comment by CaptainDero** [comment]
Try adding following option to daemon:
`--add-priority-node=45.82.66.54:8080`

**Comment by CaptainDero** [comment]
Done. Pls update to latest release.
