### ISSUE TITLE
stuck 2040/2102

### ISSUE THREAD

**Issue by spDisckord** [deroproject/derohe#4]
[testnet.zip](https://github.com/deroproject/derohe/files/6028329/testnet.zip)
windows 10 x64

**Comment by spDisckord** [comment]
[testnet_dero_windows_amd64_3.2.0-14.DEROHE.STARGATE+23022021.zip](https://github.com/deroproject/derohe/files/6028617/testnet_dero_windows_amd64_3.2.0-14.DEROHE.STARGATE%2B23022021.zip)
stuk 3032/3141 new vers. daemon dero_windows_amd64_3.2.0-14.DEROHE.STARGATE+23022021

**Comment by CaptainDero** [comment]
Fixed in latest release.
