### ISSUE TITLE
MAX_STORAGE_GAS_ATOMIC_UNITS is not big enough

### ISSUE THREAD

**Issue by g45t345rt** [deroproject/derohe#40]
Updating a bigger Smart Contract does not work.
The gas storage fee exceeds the default config limit.

https://github.com/deroproject/derohe/blob/3acbbee23416e24cc07b33de91a46c2ecc1a8ade/config/config.go#L43

I'm sending the code as hex string because I need to escape characters in json but I need unescape characters in the sc code.
```
Function UpdateCode(hexCode String) Uint64
10 IF LOAD("sc_owner") == SIGNER() THEN GOTO 30
20 RETURN 1
30 UPDATE_SC_CODE(HEXDECODE(hexCode))
40 RETURN 0
End Function
```

Right now, I'm building my own derod node with a higher config number but I don't know if this is going to work in production if other nodes have the default config limit.

**Comment by CaptainDero** [comment]
20Kb is max allowed.

**Comment by g45t345rt** [comment]
Ok, but is there a way I could send the code in base64 instead of hex to save space?

I can't send the code as plain text with json_rpc params :S

**Comment by g45t345rt** [comment]
Ok I was able to send the code as plain text with python instead of bash :)

**Comment by g45t345rt** [comment]
Ok, I was able to send the code as plain text using python instead of bash :)
