### ISSUE TITLE
--min-peers

### ISSUE THREAD

**Issue by snipeTR** [deroproject/derohe#41]
A suggestion:
why don't we put max-peers parameter like min-peers?
I think it might work.
![image](https://user-images.githubusercontent.com/31975916/159487074-d90aaadf-56aa-450b-9e36-eceef402c089.png)
![image](https://user-images.githubusercontent.com/31975916/159487711-82bd36f7-6f16-402d-95dd-88ca8c38c330.png)

**Comment by Slixe** [comment]
--min-peers must be added in launch arguments by @CaptainDero otherwise, the Parser will not accept it.
