### ISSUE TITLE
Account registration to blockchain in Liunx very high CPU

### ISSUE THREAD

**Issue by avselang** [deroproject/derohe#43]
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                  
  70719 root      20   0  711204  46444   6852 S 189.0   2.4  11:12.63 dero-wallet-cli

**Comment by avselang** [comment]
very long time

**Comment by CaptainDero** [comment]
Yes wallet is solving POW for registration.
