### ISSUE TITLE
STUCK AT BLOCK 29012/29012 block rejected by chain error 

### ISSUE THREAD

**Issue by rap143** [deroproject/derohe#45]
why am I stuck at this block height and when I run derod the node shows me that a block was rejected by chain 
DERO HE: 29012/29012 [144875/144875] P 3 TXp 0:0 NW 773.546 MH/s >MineDERO HE: 29012/29012 [144875/144875] P 3 TXp 0:0 NW 773.546 MH/s >MineDERO HE: 29012/29012 [144875/144875] P 3 TXp 0:0 NW 773.546 MH/s >MineDERO HE: 29012/29012 [144875/144875] P 3 TXp 0:0 NW 773.546 MH/s >MineDERO HE: 29012/29012 [144876/144876] P 3 TXp 0:0 NW 773.546 MH/s >Mine29/03 22:05:17  ERROR   CORE.blid_e842d3678c48632cf0598bc53ddbd026b0268beaf82d462790591400e94ad569    tx verification failed  {"txid": "1eb36aecb6ae0fbbaa59742ab0a92e3aa8428332b23011dbcd7ceea9a0388f90", "error": "Tx statement roothash mismatch ref blid bd654a98035e66bb1e8ab937682c3a5e484dba356e0aa07b7ca5ea1a939345ba expected 3cad11f170e6f31d06a62c1fad272d66b07606e9885539c66c96d083d6b38cbc actual f1e41c2f7aa2c433b3338a1415f9976148d06cdc85abe7b8138af50cad45750e"}
DERO HE: 29012/29012 [144876/144876] P 3 TXp 0:0 NW 773.546 MH/s >Mine29/03 22:05:17  ERROR   CORE.blid_e842d3678c48632cf0598bc53ddbd026b0268beaf82d462790591400e94ad569    rejecting block {"error": "TX verification failed"}
DERO HE: 29012/29012 [144876/144876] P 3 TXp 0:0 NW 773.546 MH/s >Mine29/03 22:05:17  ERROR   CORE    Block rejected by chain {"BLID": "e842d3678c48632cf0598bc53ddbd026b0268beaf82d462790591400e94ad569", "error": "Invalid TX"}
DERO HE: 29012/29012 [144876/144876] P 3 TXp 0:0 NW 773.546 MH/s >Mine29/03 22:05:17  ERROR   CORE    Block rejected by chain {"BLID": "c2cd74454c6cca6383b4b62e05eecc865482c16c8a563b0d5802b6dbd4babc5e", "error": "Past blocks are missing"}
DERO HE: 29012/29012 [144876/144876] P 3 TXp 0:0 NW 773.546 MH/s >MineDERO HE: 29012/29012 [144876/144876] P 3 TXp 0:0 NW 773.546 MH/s >Mine29/03 22:05:18  ERROR   CORE    Block rejected by chain {"BLID": "bb1a98192269714c178c966325d20f55105c2294c598fefbaa40294aa76ea97c", "error": "Past blocks are missing"}
DERO HE: 29012/29012 [144876/144876] P 3 TXp 0:0 NW 773.546 MH/s >Mine29/03 22:05:18  ERROR   CORE    Block rejected by chain {"BLID": "6da06e3b282259407cca20844e11f2613e8a1328d5d84563997d62546f39373b", "error": "Past blocks are missing"}
DERO HE: 29012/29012 [144876/144876] P 3 TXp 0:0 NW 773.546 MH/s >MineDERO HE: 29012/29012 [144876/144876] P 3 TXp 0:0 NW 773.546 MH/s >MineDERO HE: 29012/29012 [144876/144876] P 3 TXp 0:0 NW 773.546 MH/s >MineDERO HE: 29012/29012 [144876/144876] P 3 TXp 0:0 NW 773.546 MH/s >Mine

**Comment by Nelbert442** [comment]
Ensure you're running the latest binaries. https://GitHub.com/deroproject/derohe/releases/latest

Replace derod . If you get warning about corrupt chain, delete mainnet and resync with updated binaries

**Comment by thespicer21** [comment]
> Ensure you're running the latest binaries. https://GitHub.com/deroproject/derohe/releases/latest
> 
> Replace derod . If you get warning about corrupt chain, delete mainnet and resync with updated binaries

Thanks, trying that now. Might be an idea for the devs to get the docs updated as they are pointing to the broken release.

https://docs.dero.io/rtd_pages/basic_ubuntu.html
