### ISSUE TITLE
Dero wallet continues to show 0 as a balance

### ISSUE THREAD

**Issue by JeffGwi** [deroproject/derohe#50]
New version does not let me import wallet.db coins.

I tried using "Wallet Seed" and I get nothing and no coins population from previous wallet.db.

Regardless of how many times I rescan my blockchain my Dero balance comes up as 0.

I realize that Dero is using a different wallet but this shouldn't be that difficult to get your coins over to the new wallet. 

I have been at this for days and still a 0 balance.

What do you suggest?

**Comment by mrbluecoat** [comment]
Did you use the guide at https://docs.dero.io/rtd_pages/basic_cntohe.html to convert from the old (CN) format to the new (HE) format? You'll need to mine a bit on your new HE address to get at least 0.00001 DERO to complete the transfer.

**Comment by CaptainDero** [comment]
Read this https://github.com/deroproject/documentation/blob/master/DEROSWAP.txt
Join [DERO Discord](https://discord.gg/H95TJDp) and someone will send you amount required for transfer fees.
