### ISSUE TITLE
JSON-RPC bug and wallet registration issues

### ISSUE THREAD

**Issue by JamesDDaniel** [deroproject/derohe#54]
I have a couple questions regarding the JSON-RPC and command line tools.

# derohe Release66

Why is it that my daemon (connected to a miner) in testnet only mines miniblocks at one topoheight endlessly? When restarting the miner and the daemon it instantly mines at the next height.
This makes it impossible for me to register new accounts needed to test smart contracts.
Could this be the same issue as [#46](https://github.com/deroproject/derohe/issues/46)?

# derohe Release62

On this version registering new accounts works fine, but the daemon JSON-RPC handles `getsc` requests incorrectly:

I am using [the stargate RPC documentation](https://docs.dero.io/rtd_pages/dev_rpcapistargate.html), please correct me if that is not the right API.

When requesting multiple keys using the `"keysstring"` parameter, the response always only contains the value of the last key requested.
Eg. request body:
```json
{
	"id": "1",
	"method": "getsc",
	"jsonrpc": "2.0",
	"params": {
		"scid": "my_scid",
		"variables": false,
		"code": false,
		"keysstring": ["key_1", "key_2"]
	}
}
```
response:
```json
{
  "jsonrpc": "2.0",
  "id": "1",
  "result": {
    "valuesstring": [
      "value_of_key_2"
    ],
    "balance": 0,
    "code": "",
    "status": "OK"
  }
}
```
In the [source code](https://github.com/deroproject/derohe/blob/main/cmd/derod/rpc/rpc_dero_getsc.go#L158) it uses Golang’s `append()` function, so this should not be the problem? I am not proficient in Golang, so I cannot do any proper code analysis.

Sadly, this makes the JSON-RPC unusable to efficiently obtain smart contract variables.

I am aware that I could obtain all the key-value pairs using the parameter `"variables": true`, but that seems to be highly inefficient because my use case is fetching _few_ keys _often_ (basically [this](https://github.com/deroproject/derohe/issues/34#issuecomment-1068036387)).

If this method is not inefficient because of some graviton-magic, please let me know and I’ll base my project on that.

# apparent smart contract size limit

I could not find any information on whether there actually _is_ a size limit for smart contracts (in testnet).
I have a smart contract that is ca. 19.17kb.
I ensured that it is correct and parseable. However, when adding an arbitrary (correct) line, it won’t be accepted by the daemon. The code can be seen using the explorer (`SC Arguments: [...]`). The explorer does not show any values, neither does it list the code in a structured way. The smart contract does not contain any values (`Initialize()` is not called) and cannot be invoked.

All this does not happen when staying below ca. 19.17kb smart contract size.
I have enough unlocked funds in my testnet wallet, so that is no concern.

What is my problem here and is there a limit to a smart contract’s size?

I already posted on the [DERO community forum](https://forum.dero.io/t/json-rpc-behaves-incorrecly-and-testnet-setup/1974), but did not get any help.
This post is about a potential bug, so I assume this to be the right place to ask.

**Comment by Nelbert442** [comment]
Replied to your similar posting on the forum in which it was originally posted, sorry for the delays. 

Give release 73 a go , in regards to your version questions for mining solo testnet as well as getsc calls. Solo testnet in release 66 appeared to work if you had 1+ peers but now should be covered as well via release 73 but will just give you an err related to peers and stale detail if you're mining blocks etc. locally to your own private testnet. If you can, add some peers for proper testing etc., however I know it isn't always possible. You can also leverage the simulator with lots of nice functionalities for SC testing etc.

https://forum.dero.io/t/json-rpc-behaves-incorrecly-and-testnet-setup/1974/2?u=nelbert442

**Comment by Nelbert442** [comment]
Related to gas storage limit (https://forum.dero.io/t/json-rpc-behaves-incorrecly-and-testnet-setup/1974/4):

20kb limit on SC.

Config max limit:
https://github.com/deroproject/derohe/blob/main/config/config.go#L44

Set max storage limit:
https://github.com/deroproject/derohe/blob/main/dvm/sc.go#L243

Error / fail out if reached:
https://github.com/deroproject/derohe/blob/main/dvm/dvm.go#L452

**Comment by JamesDDaniel** [comment]
Thank you very much for your detailed response!
The daemon JSON-RPC works as expected on Release73.

I assume the smart contract size limit is defined on the network-level, not client-side (eg. I cannot just change it for deploying a bigger contract).
Is the size limit the same on mainnet and testnet?
Are there any plans to change this value?

**Comment by JamesDDaniel** [comment]
Thanks a lot, I can now continue my work!
Closing the issue!
