### ISSUE TITLE
Vulnerability i fount in the test net || Tynorn

### ISSUE THREAD

**Issue by tynorn1** [deroproject/derohe#6]
Is there any tips for the genuine Vulnerability

**Comment by tynorn1** [comment]
@CaptainDero

**Comment by tynorn1** [comment]
Last time i fount an DOS attack is possible on Testnet need an fix for it i can share the evidence.
[dero.pdf](https://github.com/deroproject/derohe/files/6153878/dero.pdf)

**Comment by CaptainDero** [comment]
Please report bugs in DERO code only here. For bugs in other vendors/software codes, please contact them directly.
