### ISSUE TITLE
Malicious miners are not getting banned

### ISSUE THREAD

**Issue by jon4hz** [deroproject/derohe#65]
It seems that a malicious miner can just spam wrong shares to a node without getting banned. This causes an insane amount of log flooding an is extremely annoying. Being able to use the derod console is pretty important to operate a node and such flooding makes it almost impossible. 
Enough flooding can also cause quite some load on the CPU. So the fact that these miners are not getting banned makes the node easily vulnerable to ddos attacks. 

To recreate the problem, you can simply use a miner pre v96 fork and start mining. A modification of the software isn't required.

**Comment by CaptainDero** [comment]
Noted.

**Comment by CaptainDero** [comment]
Fixed in next release.
Such Miners are not being banned but all their future shares are ignored & warning message broadcasted to them.

**Comment by ei8ht187** [comment]
New version is here, is this fixed?
