### ISSUE TITLE
Vulnerability  Findings

### ISSUE THREAD

**Issue by tynorn1** [deroproject/derohe#7]
Please find the vulnerability finding as attachment and promote me like vulnerability testers
if u are interest me like testers please promote
My dero address : dERoaGTABmXUFqNCLMDtxAeF6kTgVnYpwjnZqSDKr72wA8nkaji2M9e1zyogd8pFYtX4bZKeybEvfP2y82heRKpW5GeRpNBc6K
[derosecuritybug.pdf](https://github.com/deroproject/derohe/files/6199135/derosecuritybug.pdf)

**Comment by CaptainDero** [comment]
Please report bugs in DERO code only here. For other vendors/software please contact them directly.
