### ISSUE TITLE
Transfer command when exited from menu mode doesn't work.

### ISSUE THREAD

**Issue by downystreet** [deroproject/derohe#8]
Version 3.2.14-1.DEROHE.STARGATE+28022021 OS:linux ARCH:amd64

When exited from menu mode the transfer command doesn't work. When entering transfer (address) (amount) into the command prompt, upon hitting (enter) nothing happens and it returns to the command prompt.

**Comment by CaptainDero** [comment]
Can you post the screenshot of above.

**Comment by downystreet** [comment]
![derohetransfer](https://user-images.githubusercontent.com/63488055/125381737-6bcf9b00-e362-11eb-8647-1ffdec38d81f.png)
