### ISSUE TITLE
Question: When starting Stargate binary folder need to be persistent?

### ISSUE THREAD

**Issue by jcalfee** [deroproject/derohe#83]
I have a working dir HOME that is different from the Stargate binary folder.  I noticed it creates the mainnet in HOME and probably the wallet.  But Stargate tries to write log files to the binary folder (I had to make it writable to get ride of an error writing to `derod-linux-amd64.log`).  I made the binary folder writable, but does the binary folder have to be persistent or just the HOME folder?

**Comment by Nelbert442** [comment]
Generally if it can write, the mainnet/testnet (depending on network) directories (which hold chain data) are created in same dir as binary , unless you modified with one of the data directory flags.

WRT derod , only the mainnet/testnet directories with chain data need to persist. Rest is just logs. 

WRT wallet , the wallet.db (or other if using --wallet-name) , creates in same dir as binary by default and should persist unless you want to restore from seed every time (which also is fine/possible).

**Comment by jcalfee** [comment]
Thanks for the clarification.  Sounds like keeping the log around only for one docker session is safe.

I did not use any flags.  I just ran derod from the HOME folder and the mainnet appeared in HOME.  I have not checked the wallet.db yet but of course I'll be keeping a close eye on that.  Atantlis was using the pwd for the wallet by default.
