### ISSUE TITLE
we have or others have deviated too much.you may have to use --sync-node option

### ISSUE THREAD

**Issue by jcalfee** [deroproject/derohe#84]
I must be the first to see this:

>25/07 13:14:50  ERROR   P2P.outgoing.95.112.131.187:47911       we have or others have deviated too much.you may have to use --sync-node option      {"our topoheight": 61613, "peer topoheight start": 0}
>25/07 15:28:31  ERROR   P2P.outgoing.95.112.131.187:47911       we have or others have deviated too much.you may have to use --sync-node option   {"our topoheight": 97453, "peer topoheight start": 0}

The message makes it sound optional, but the comment not so much:

> // we must somehow notify that deviation is **way** too much and manual interaction **is necessary**, so as any bug for chain deviationmay be detected

I not sure if it is best to go on the 1st or the later, keep syncing then run `--sync-node`, stop syncing now and run `--sync-node`, resort to a rsync found in another issue here, or the something else.

**Comment by Nelbert442** [comment]
As long as you are still syncing forward you're all good. By the looks you are syncing up a newer node so can safely ignore these messages. If you were at/near chain height and deviated then received these then could be cause for sync-node to be used but no issues ATM. You may have some peer that is not syncing but connected , and can ignore.

**Comment by jcalfee** [comment]
Still syncing forward .. That makes a lot of since but I think what your saying here would make for a much better comment in the code.  At least we have it documented here in an issue now.  Thank you.
