### ISSUE TITLE
CLI Wallet just freezes after third opening of TX history

### ISSUE THREAD

**Issue by ei8ht187** [deroproject/derohe#96]
As written in the title. The CLI wallet just freezes, no logs or errors or similiar when you choose option 13, return back to main menu, choose option 13, return back to main menu, and do this again once, or maybe twice. The CLI wallet has then to be killed and restartet to get working again.

**Comment by CaptainDero** [comment]
Pls update to latest release. 
If still any issue please re-open the issue.
