### ISSUE TITLE
Error connecting to server

### ISSUE THREAD

**Issue by federimau** [deroproject/derohe#99]
Today dero miner dont connect to server. see picture
![dero](https://user-images.githubusercontent.com/112592916/190912793-835863b1-fb63-4480-a8ba-eaaf84413309.jpg)

**Comment by federimau** [comment]
Tried to change ports (4300, 4301. 4302). Error connecting to server continues

**Comment by 8lecramm** [comment]
Hi,
this is not the official Dero miner.
Please contact the pool operator.
